// Env de WhatsApp fijada ANTES de cualquier import: lib/whatsapp/config.ts
// captura estos valores en sus const al cargar, así los tests del router/webhook
// no dependen del orden de importación entre archivos.
process.env.WHATSAPP_API_TOKEN ||= "test-wa-token";
process.env.WHATSAPP_PHONE_NUMBER_ID ||= "123456789";
process.env.WHATSAPP_APP_SECRET ||= "test-wa-secret";

await import("./rate-limit.test.ts");
await import("./schema.test.ts");
await import("./ai.test.ts");
await import("./api-chat.test.ts");
await import("./api-lead.test.ts");
await import("./lead-forms.test.ts");
await import("./lead-forms-v2.test.ts");
await import("./integrations/apollo.test.ts");
await import("./integrations/mail.test.ts");
await import("./integrations/monday.test.ts");
await import("./db-fallback.test.ts");
await import("./admin-auth.test.ts");
await import("./whatsapp-webhook.test.ts");
await import("./whatsapp-router.test.ts");
await import("./admin-conversations.test.ts");
await import("./audit.test.ts");
await import("./admin-rate-limit.test.ts");
await import("./rbac.test.ts");
await import("./password.test.ts");
await import("./crm-schema.test.ts");
await import("./sales-calc.test.ts");
await import("./catalog-schema.test.ts");
await import("./inventory-schema.test.ts");
await import("./orders-schema.test.ts");
await import("./billing-schema.test.ts");
await import("./purchases-treasury-schema.test.ts");
await import("./support-schema.test.ts");
await import("./warranties-schema.test.ts");
await import("./services-schema.test.ts");
await import("./accounting-schema.test.ts");
await import("./json-ld.test.ts");
await import("./team-schema.test.ts");
await import("./alerts-notify.test.ts");
await import("./accounting-balance.test.ts");
await import("./settings-merge.test.ts");
await import("./crypto-secrets.test.ts");
await import("./attribution.test.ts");
await import("./ads-conversions.test.ts");
await import("./ads-performance.test.ts");
await import("./marketing-social.test.ts");
await import("./air-config.test.ts");
await import("./air-mapper.test.ts");
await import("./air-client.test.ts");
await import("./air-preorder.test.ts");
